apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-fluentd
  labels:
    app: prometheus-fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-fluentd
  template:
    metadata:
      labels:
        app: prometheus-fluentd
    spec:
      containers:
      - name: remote
        image: quay.io/ryotarai/prometheus-remote-fluentd:v0.0.4
        args: ["-fluent-host=localhost", "-fluent-tag=prometheus.samples"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"

      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.2-debian-s3
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "REPLACE_THIS"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: prometheus-fluentd
              key: aws_secret_access_key
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 24224
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc

      volumes:
      - name: config
        configMap:
          name: prometheus-fluentd
